# Generated by Django 5.0.1 on 2025-06-14 04:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barberiaapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Barbero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=255)),
                ('cortes_destacados', models.TextField()),
                ('especialidad', models.CharField(max_length=100)),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('contraseña', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Corte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('barba', 'Barba'), ('cabello', 'Cabello'), ('combo', 'Cabello + Barba'), ('premium', 'Otros')], max_length=20)),
                ('titulo', models.CharField(max_length=100)),
                ('duracion', models.PositiveIntegerField()),
                ('precio', models.PositiveIntegerField()),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField(blank=True)),
                ('editado', models.BooleanField(default=False)),
                ('realizada', models.BooleanField(default=False)),
                ('barbero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barberiaapp.barbero')),
                ('corte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barberiaapp.corte')),
            ],
        ),
    ]
