# Generated by Django 5.0.1 on 2025-06-16 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barberiaapp', '0002_barbero_corte_reserva'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='realizada',
        ),
        migrations.AddField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('realizada', 'Realizada'), ('cancelada', 'Cancelada'), ('no_asistio', 'No asistió')], default='pendiente', max_length=20),
        ),
    ]
