# Generated by Django 5.0.1 on 2025-11-05 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barberiaapp', '0004_remove_cliente_telefono_cliente_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('contraseña', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='barbero',
            name='disponible',
            field=models.BooleanField(default=True),
        ),
    ]
