# Generated by Django 5.0.1 on 2025-11-05 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barberiaapp', '0005_admin_barbero_disponible'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='admin',
            name='contraseña',
            field=models.CharField(max_length=255),
        ),
    ]
